import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
    await prisma.word.createMany({
        data: [
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "하늘",
                "japanese": ["そら", "空"],
                "hiragana": ["そら"],
                "katakana": [],
                "kanzi": ["空"],
                "english": ["sky"],
                "meaning": "하늘"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "바다",
                "japanese": ["うみ", "海"],
                "hiragana": ["うみ"],
                "katakana": [],
                "kanzi": ["海"],
                "english": ["sea", "ocean"],
                "meaning": "바다"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "강",
                "japanese": ["かわ", "川"],
                "hiragana": ["かわ"],
                "katakana": [],
                "kanzi": ["川"],
                "english": ["river"],
                "meaning": "강"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "산",
                "japanese": ["やま", "山"],
                "hiragana": ["やま"],
                "katakana": [],
                "kanzi": ["山"],
                "english": ["mountain"],
                "meaning": "산"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "나무",
                "japanese": ["き", "木"],
                "hiragana": ["き"],
                "katakana": [],
                "kanzi": ["木"],
                "english": ["tree"],
                "meaning": "나무"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "날씨",
                "japanese": ["てんき", "天気"],
                "hiragana": ["てんき"],
                "katakana": [],
                "kanzi": ["天気"],
                "english": ["weather"],
                "meaning": "날씨"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "불",
                "japanese": ["ひ", "火"],
                "hiragana": ["ひ"],
                "katakana": [],
                "kanzi": ["火"],
                "english": ["fire"],
                "meaning": "불"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "물",
                "japanese": ["みず", "水"],
                "hiragana": ["みず"],
                "katakana": [],
                "kanzi": ["水"],
                "english": ["water"],
                "meaning": "물"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "연못",
                "japanese": ["いけ", "池"],
                "hiragana": ["いけ"],
                "katakana": [],
                "kanzi": ["池"],
                "english": ["pond"],
                "meaning": "연못"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "공기",
                "japanese": ["くうき", "空気"],
                "hiragana": ["くうき"],
                "katakana": [],
                "kanzi": ["空気"],
                "english": ["air"],
                "meaning": "공기"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "계절",
                "japanese": ["きせつ", "季節"],
                "hiragana": ["きせつ"],
                "katakana": [],
                "kanzi": ["季節"],
                "english": ["season"],
                "meaning": "계절"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "경치",
                "japanese": ["けしき", "景色"],
                "hiragana": ["けしき"],
                "katakana": [],
                "kanzi": ["景色"],
                "english": ["scenery"],
                "meaning": "경치"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "동물",
                "japanese": ["どうぶつ", "動物"],
                "hiragana": ["どうぶつ"],
                "katakana": [],
                "kanzi": ["動物"],
                "english": ["animal"],
                "meaning": "동물"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "새",
                "japanese": ["とり", "鳥"],
                "hiragana": ["とり"],
                "katakana": [],
                "kanzi": ["鳥"],
                "english": ["bird"],
                "meaning": "새"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "봄",
                "japanese": ["はる", "春"],
                "hiragana": ["はる"],
                "katakana": [],
                "kanzi": ["春"],
                "english": ["spring"],
                "meaning": "봄"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "여름",
                "japanese": ["なつ", "夏"],
                "hiragana": ["なつ"],
                "katakana": [],
                "kanzi": ["夏"],
                "english": ["summer"],
                "meaning": "여름"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "가을",
                "japanese": ["あき", "秋"],
                "hiragana": ["あき"],
                "katakana": [],
                "kanzi": ["秋"],
                "english": ["autumn", "fall"],
                "meaning": "가을"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "겨울",
                "japanese": ["ふゆ", "冬"],
                "hiragana": ["ふゆ"],
                "katakana": [],
                "kanzi": ["冬"],
                "english": ["winter"],
                "meaning": "겨울"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "꽃",
                "japanese": ["はな", "花"],
                "hiragana": ["はな"],
                "katakana": [],
                "kanzi": ["花"],
                "english": ["flower"],
                "meaning": "꽃"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "비",
                "japanese": ["あめ", "雨"],
                "hiragana": ["あめ"],
                "katakana": [],
                "kanzi": ["雨"],
                "english": ["rain"],
                "meaning": "비"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "눈",
                "japanese": ["ゆき", "雪"],
                "hiragana": ["ゆき"],
                "katakana": [],
                "kanzi": ["雪"],
                "english": ["snow"],
                "meaning": "눈"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "바람",
                "japanese": ["かぜ", "風"],
                "hiragana": ["かぜ"],
                "katakana": [],
                "kanzi": ["風"],
                "english": ["wind"],
                "meaning": "바람"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "구름",
                "japanese": ["くも", "雲"],
                "hiragana": ["くも"],
                "katakana": [],
                "kanzi": ["雲"],
                "english": ["cloud"],
                "meaning": "구름"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "천둥",
                "japanese": ["かみなり", "雷"],
                "hiragana": ["かみなり"],
                "katakana": [],
                "kanzi": ["雷"],
                "english": ["thunder"],
                "meaning": "천둥"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "맑음",
                "japanese": ["はれ", "晴れ"],
                "hiragana": ["はれ"],
                "katakana": [],
                "kanzi": ["晴れ"],
                "english": ["clear weather"],
                "meaning": "맑음"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "태풍",
                "japanese": ["たいふう", "台風"],
                "hiragana": ["たいふう"],
                "katakana": [],
                "kanzi": ["台風"],
                "english": ["typhoon"],
                "meaning": "태풍"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "개",
                "japanese": ["いぬ", "犬"],
                "hiragana": ["いぬ"],
                "katakana": [],
                "kanzi": ["犬"],
                "english": ["dog"],
                "meaning": "개"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "고양이",
                "japanese": ["ねこ", "猫"],
                "hiragana": ["ねこ"],
                "katakana": [],
                "kanzi": ["猫"],
                "english": ["cat"],
                "meaning": "고양이"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "보다",
                "japanese": ["みる", "見る"],
                "hiragana": ["みる"],
                "katakana": [],
                "kanzi": ["見る"],
                "english": ["to see", "to look"],
                "meaning": "보다"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "보이다",
                "japanese": ["みえる", "見える"],
                "hiragana": ["みえる"],
                "katakana": [],
                "kanzi": ["見える"],
                "english": ["to be visible"],
                "meaning": "보이다"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "보여주다",
                "japanese": ["みせる", "見せる"],
                "hiragana": ["みせる"],
                "katakana": [],
                "kanzi": ["見せる"],
                "english": ["to show"],
                "meaning": "보여주다"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "피다",
                "japanese": ["さく", "咲く"],
                "hiragana": ["さく"],
                "katakana": [],
                "kanzi": ["咲く"],
                "english": ["to bloom"],
                "meaning": "피다"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "죽다",
                "japanese": ["しぬ", "死ぬ"],
                "hiragana": ["しぬ"],
                "katakana": [],
                "kanzi": ["死ぬ"],
                "english": ["to die"],
                "meaning": "죽다"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "날다",
                "japanese": ["とぶ", "飛ぶ"],
                "hiragana": ["とぶ"],
                "katakana": [],
                "kanzi": ["飛ぶ"],
                "english": ["to fly"],
                "meaning": "날다"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "맑다",
                "japanese": ["はれる", "晴れる"],
                "hiragana": ["はれる"],
                "katakana": [],
                "kanzi": ["晴れる"],
                "english": ["to clear up"],
                "meaning": "맑다"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "(비, 눈 등이) 내리다",
                "japanese": ["ふる", "降る"],
                "hiragana": ["ふる"],
                "katakana": [],
                "kanzi": ["降る"],
                "english": ["to fall (rain, snow, etc.)"],
                "meaning": "내리다"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "(소리가) 들리다",
                "japanese": ["きこえる", "聞こえる"],
                "hiragana": ["きこえる"],
                "katakana": [],
                "kanzi": ["聞こえる"],
                "english": ["to be audible"],
                "meaning": "들리다"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "(우산을) 쓰다",
                "japanese": ["さす", "差す"],
                "hiragana": ["さす"],
                "katakana": [],
                "kanzi": ["差す"],
                "english": ["to hold up (an umbrella)"],
                "meaning": "쓰다"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "버리다",
                "japanese": ["すてる", "捨てる"],
                "hiragana": ["すてる"],
                "katakana": [],
                "kanzi": ["捨てる"],
                "english": ["to throw away"],
                "meaning": "버리다"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "(새가) 울다",
                "japanese": ["なく", "鳴く"],
                "hiragana": ["なく"],
                "katakana": [],
                "kanzi": ["鳴く"],
                "english": ["to chirp", "to sing (birds)"],
                "meaning": "울다"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "(바람이) 불다",
                "japanese": ["ふく", "吹く"],
                "hiragana": ["ふく"],
                "katakana": [],
                "kanzi": ["吹く"],
                "english": ["to blow (wind)"],
                "meaning": "불다"
            },
            {
                "title": "DAY 2 자연·동물",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "(산으로) 오르다",
                "japanese": ["のぼる", "登る"],
                "hiragana": ["のぼる"],
                "katakana": [],
                "kanzi": ["登る"],
                "english": ["to climb (a mountain)"],
                "meaning": "오르다"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "1일",
                "japanese": ["ついたち", "一日"],
                "hiragana": ["ついたち"],
                "katakana": [],
                "kanzi": ["一日"],
                "english": ["1st day"],
                "meaning": "1일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "2일",
                "japanese": ["ふつか", "二日"],
                "hiragana": ["ふつか"],
                "katakana": [],
                "kanzi": ["二日"],
                "english": ["2nd day"],
                "meaning": "2일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "3일",
                "japanese": ["みっか", "三日"],
                "hiragana": ["みっか"],
                "katakana": [],
                "kanzi": ["三日"],
                "english": ["3rd day"],
                "meaning": "3일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "4일",
                "japanese": ["よっか", "四日"],
                "hiragana": ["よっか"],
                "katakana": [],
                "kanzi": ["四日"],
                "english": ["4th day"],
                "meaning": "4일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "5일",
                "japanese": ["いつか", "五日"],
                "hiragana": ["いつか"],
                "katakana": [],
                "kanzi": ["五日"],
                "english": ["5th day"],
                "meaning": "5일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "6일",
                "japanese": ["むいか", "六日"],
                "hiragana": ["むいか"],
                "katakana": [],
                "kanzi": ["六日"],
                "english": ["6th day"],
                "meaning": "6일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "7일",
                "japanese": ["なのか", "七日"],
                "hiragana": ["なのか"],
                "katakana": [],
                "kanzi": ["七日"],
                "english": ["7th day"],
                "meaning": "7일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "8일",
                "japanese": ["ようか", "八日"],
                "hiragana": ["ようか"],
                "katakana": [],
                "kanzi": ["八日"],
                "english": ["8th day"],
                "meaning": "8일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "9일",
                "japanese": ["ここのか", "九日"],
                "hiragana": ["ここのか"],
                "katakana": [],
                "kanzi": ["九日"],
                "english": ["9th day"],
                "meaning": "9일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "10일",
                "japanese": ["とおか", "十日"],
                "hiragana": ["とおか"],
                "katakana": [],
                "kanzi": ["十日"],
                "english": ["10th day"],
                "meaning": "10일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "11일",
                "japanese": ["じゅういちにち", "十一日"],
                "hiragana": ["じゅういちにち"],
                "katakana": [],
                "kanzi": ["十一日"],
                "english": ["11th day"],
                "meaning": "11일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "12일",
                "japanese": ["じゅうににち", "十二日"],
                "hiragana": ["じゅうににち"],
                "katakana": [],
                "kanzi": ["十二日"],
                "english": ["12th day"],
                "meaning": "12일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "13일",
                "japanese": ["じゅうさんにち", "十三日"],
                "hiragana": ["じゅうさんにち"],
                "katakana": [],
                "kanzi": ["十三日"],
                "english": ["13th day"],
                "meaning": "13일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "14일",
                "japanese": ["じゅうよっか", "十四日"],
                "hiragana": ["じゅうよっか"],
                "katakana": [],
                "kanzi": ["十四日"],
                "english": ["14th day"],
                "meaning": "14일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "15일",
                "japanese": ["じゅうごにち", "十五日"],
                "hiragana": ["じゅうごにち"],
                "katakana": [],
                "kanzi": ["十五日"],
                "english": ["15th day"],
                "meaning": "15일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "16일",
                "japanese": ["じゅうろくにち", "十六日"],
                "hiragana": ["じゅうろくにち"],
                "katakana": [],
                "kanzi": ["十六日"],
                "english": ["16th day"],
                "meaning": "16일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "17일",
                "japanese": ["じゅうしちにち", "十七日"],
                "hiragana": ["じゅうしちにち"],
                "katakana": [],
                "kanzi": ["十七日"],
                "english": ["17th day"],
                "meaning": "17일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "18일",
                "japanese": ["じゅうはちにち", "十八日"],
                "hiragana": ["じゅうはちにち"],
                "katakana": [],
                "kanzi": ["十八日"],
                "english": ["18th day"],
                "meaning": "18일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "19일",
                "japanese": ["じゅうくにち", "十九日"],
                "hiragana": ["じゅうくにち"],
                "katakana": [],
                "kanzi": ["十九日"],
                "english": ["19th day"],
                "meaning": "19일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "20일",
                "japanese": ["はつか", "二十日"],
                "hiragana": ["はつか"],
                "katakana": [],
                "kanzi": ["二十日"],
                "english": ["20th day"],
                "meaning": "20일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "21일",
                "japanese": ["にじゅういちにち", "二十一日"],
                "hiragana": ["にじゅういちにち"],
                "katakana": [],
                "kanzi": ["二十一日"],
                "english": ["21st day"],
                "meaning": "21일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "22일",
                "japanese": ["にじゅうににち", "二十二日"],
                "hiragana": ["にじゅうににち"],
                "katakana": [],
                "kanzi": ["二十二日"],
                "english": ["22nd day"],
                "meaning": "22일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "23일",
                "japanese": ["にじゅうさんにち", "二十三日"],
                "hiragana": ["にじゅうさんにち"],
                "katakana": [],
                "kanzi": ["二十三日"],
                "english": ["23rd day"],
                "meaning": "23일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "24일",
                "japanese": ["にじゅうよっか", "二十四日"],
                "hiragana": ["にじゅうよっか"],
                "katakana": [],
                "kanzi": ["二十四日"],
                "english": ["24th day"],
                "meaning": "24일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "25일",
                "japanese": ["にじゅうごにち", "二十五日"],
                "hiragana": ["にじゅうごにち"],
                "katakana": [],
                "kanzi": ["二十五日"],
                "english": ["25th day"],
                "meaning": "25일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "26일",
                "japanese": ["にじゅうろくにち", "二十六日"],
                "hiragana": ["にじゅうろくにち"],
                "katakana": [],
                "kanzi": ["二十六日"],
                "english": ["26th day"],
                "meaning": "26일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "27일",
                "japanese": ["にじゅうしちにち", "二十七日"],
                "hiragana": ["にじゅうしちにち"],
                "katakana": [],
                "kanzi": ["二十七日"],
                "english": ["27th day"],
                "meaning": "27일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "28일",
                "japanese": ["にじゅうはちにち", "二十八日"],
                "hiragana": ["にじゅうはちにち"],
                "katakana": [],
                "kanzi": ["二十八日"],
                "english": ["28th day"],
                "meaning": "28일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "29일",
                "japanese": ["にじゅうくにち", "二十九日"],
                "hiragana": ["にじゅうくにち"],
                "katakana": [],
                "kanzi": ["二十九日"],
                "english": ["29th day"],
                "meaning": "29일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "30일",
                "japanese": ["さんじゅうにち", "三十日"],
                "hiragana": ["さんじゅうにち"],
                "katakana": [],
                "kanzi": ["三十日"],
                "english": ["30th day"],
                "meaning": "30일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "31일",
                "japanese": ["さんじゅういちにち", "三十一日"],
                "hiragana": ["さんじゅういちにち"],
                "katakana": [],
                "kanzi": ["三十一日"],
                "english": ["31st day"],
                "meaning": "31일"
            },
            {
                "title": "DAY 2 날짜",
                "chapter": "일(日)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "몇 일",
                "japanese": ["なんにち", "何日"],
                "hiragana": ["なんにち"],
                "katakana": [],
                "kanzi": ["何日"],
                "english": ["what day", "how many days"],
                "meaning": "몇 일"
            },
            {
                "title": "DAY 2 형용사",
                "chapter": "イ형용사",
                "level": "N5",
                "wordClass": "형용사",
                "korean": "밝다",
                "japanese": ["あかるい", "明るい"],
                "hiragana": ["あかるい"],
                "katakana": [],
                "kanzi": ["明るい"],
                "english": ["bright"],
                "meaning": "밝다"
            },
            {
                "title": "DAY 2 형용사",
                "chapter": "イ형용사",
                "level": "N5",
                "wordClass": "형용사",
                "korean": "따뜻하다",
                "japanese": ["あたたかい", "暖かい"],
                "hiragana": ["あたたかい"],
                "katakana": [],
                "kanzi": ["暖かい"],
                "english": ["warm"],
                "meaning": "따뜻하다"
            },
            {
                "title": "DAY 2 형용사",
                "chapter": "イ형용사",
                "level": "N5",
                "wordClass": "형용사",
                "korean": "춥다",
                "japanese": ["さむい", "寒い"],
                "hiragana": ["さむい"],
                "katakana": [],
                "kanzi": ["寒い"],
                "english": ["cold"],
                "meaning": "춥다"
            },
            {
                "title": "DAY 2 형용사",
                "chapter": "イ형용사",
                "level": "N5",
                "wordClass": "형용사",
                "korean": "어둡다",
                "japanese": ["くらい", "暗い"],
                "hiragana": ["くらい"],
                "katakana": [],
                "kanzi": ["暗い"],
                "english": ["dark"],
                "meaning": "어둡다"
            },
            {
                "title": "DAY 2 형용사",
                "chapter": "イ형용사",
                "level": "N5",
                "wordClass": "형용사",
                "korean": "덥다",
                "japanese": ["あつい", "暑い"],
                "hiragana": ["あつい"],
                "katakana": [],
                "kanzi": ["暑い"],
                "english": ["hot"],
                "meaning": "덥다"
            },
            {
                "title": "DAY 2 형용사",
                "chapter": "イ형용사",
                "level": "N5",
                "wordClass": "형용사",
                "korean": "시원하다",
                "japanese": ["すずしい", "涼しい"],
                "hiragana": ["すずしい"],
                "katakana": [],
                "kanzi": ["涼しい"],
                "english": ["cool"],
                "meaning": "시원하다"
            }
        ],
        skipDuplicates: true,
    });
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    }); 