import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
    await prisma.word.createMany({
        data: [
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "아침",
                "japanese": ["あさ", "朝"],
                "hiragana": ["あさ"],
                "katakana": [],
                "kanzi": ["朝"],
                "english": ["morning"],
                "meaning": "아침"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "점심, 낮",
                "japanese": ["ひる", "昼"],
                "hiragana": ["ひる"],
                "katakana": [],
                "kanzi": ["昼"],
                "english": ["noon", "daytime"],
                "meaning": "점심, 낮"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "저녁",
                "japanese": ["ばん", "晩"],
                "hiragana": ["ばん"],
                "katakana": [],
                "kanzi": ["晩"],
                "english": ["evening"],
                "meaning": "저녁"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "밤",
                "japanese": ["よる", "夜"],
                "hiragana": ["よる"],
                "katakana": [],
                "kanzi": ["夜"],
                "english": ["night"],
                "meaning": "밤"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "오늘 아침",
                "japanese": ["けさ", "今朝"],
                "hiragana": ["けさ"],
                "katakana": [],
                "kanzi": ["今朝"],
                "english": ["this morning"],
                "meaning": "오늘 아침"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "오늘 밤",
                "japanese": ["こんばん", "今晩"],
                "hiragana": ["こんばん"],
                "katakana": [],
                "kanzi": ["今晩"],
                "english": ["this evening", "tonight"],
                "meaning": "오늘 밤"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "어제 저녁",
                "japanese": ["ゆうべ", "夕べ"],
                "hiragana": ["ゆうべ"],
                "katakana": [],
                "kanzi": ["夕べ"],
                "english": ["last night", "yesterday evening"],
                "meaning": "어제 저녁"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "오전",
                "japanese": ["ごぜん", "午前"],
                "hiragana": ["ごぜん"],
                "katakana": [],
                "kanzi": ["午前"],
                "english": ["morning", "A.M."],
                "meaning": "오전"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "오후",
                "japanese": ["ごご", "午後"],
                "hiragana": ["ごご"],
                "katakana": [],
                "kanzi": ["午後"],
                "english": ["afternoon", "P.M."],
                "meaning": "오후"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "하루",
                "japanese": ["いちにち", "一日"],
                "hiragana": ["いちにち"],
                "katakana": [],
                "kanzi": ["一日"],
                "english": ["one day"],
                "meaning": "하루"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "설날",
                "japanese": ["しょうがつ", "正月"],
                "hiragana": ["しょうがつ"],
                "katakana": [],
                "kanzi": ["正月"],
                "english": ["New Year's Day"],
                "meaning": "설날"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "생일",
                "japanese": ["たんじょうび", "誕生日"],
                "hiragana": ["たんじょうび"],
                "katakana": [],
                "kanzi": ["誕生日"],
                "english": ["birthday"],
                "meaning": "생일"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "반년",
                "japanese": ["はんとし", "半年"],
                "hiragana": ["はんとし"],
                "katakana": [],
                "kanzi": ["半年"],
                "english": ["half a year"],
                "meaning": "반년"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "이틀 전",
                "japanese": ["おととい", "一昨日"],
                "hiragana": ["おととい"],
                "katakana": [],
                "kanzi": ["一昨日"],
                "english": ["the day before yesterday"],
                "meaning": "이틀 전"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "시작",
                "japanese": ["はじめ", "始め"],
                "hiragana": ["はじめ"],
                "katakana": [],
                "kanzi": ["始め"],
                "english": ["start", "beginning"],
                "meaning": "시작"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "매일",
                "japanese": ["まいにち", "毎日"],
                "hiragana": ["まいにち"],
                "katakana": [],
                "kanzi": ["毎日"],
                "english": ["every day"],
                "meaning": "매일"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "매주",
                "japanese": ["まいしゅう", "毎週"],
                "hiragana": ["まいしゅう"],
                "katakana": [],
                "kanzi": ["毎週"],
                "english": ["every week"],
                "meaning": "매주"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "매달",
                "japanese": ["まいげつ", "毎月"],
                "hiragana": ["まいげつ"],
                "katakana": [],
                "kanzi": ["毎月"],
                "english": ["every month"],
                "meaning": "매달"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "매년",
                "japanese": ["まいねん", "毎年"],
                "hiragana": ["まいねん"],
                "katakana": [],
                "kanzi": ["毎年"],
                "english": ["every year"],
                "meaning": "매년"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "매일 아침",
                "japanese": ["まいあさ", "毎朝"],
                "hiragana": ["まいあさ"],
                "katakana": [],
                "kanzi": ["毎朝"],
                "english": ["every morning"],
                "meaning": "매일 아침"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "매일 저녁",
                "japanese": ["まいばん", "毎晩"],
                "hiragana": ["まいばん"],
                "katakana": [],
                "kanzi": ["毎晩"],
                "english": ["every evening"],
                "meaning": "매일 저녁"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "나중, 다음",
                "japanese": ["あと", "後"],
                "hiragana": ["あと"],
                "katakana": [],
                "kanzi": ["後"],
                "english": ["later", "after"],
                "meaning": "나중, 다음"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "앞, 먼저",
                "japanese": ["まえ", "前"],
                "hiragana": ["まえ"],
                "katakana": [],
                "kanzi": ["前"],
                "english": ["before", "ahead"],
                "meaning": "앞, 먼저"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "지금",
                "japanese": ["いま", "今"],
                "hiragana": ["いま"],
                "katakana": [],
                "kanzi": ["今"],
                "english": ["now"],
                "meaning": "지금"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "먼저",
                "japanese": ["さき", "先"],
                "hiragana": ["さき"],
                "katakana": [],
                "kanzi": ["先"],
                "english": ["first", "earlier"],
                "meaning": "먼저"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "다음",
                "japanese": ["つぎ", "次"],
                "hiragana": ["つぎ"],
                "katakana": [],
                "kanzi": ["次"],
                "english": ["next"],
                "meaning": "다음"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "최후",
                "japanese": ["さいご", "最後"],
                "hiragana": ["さいご"],
                "katakana": [],
                "kanzi": ["最後"],
                "english": ["last", "final"],
                "meaning": "최후"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "최초",
                "japanese": ["さいしょ", "最初"],
                "hiragana": ["さいしょ"],
                "katakana": [],
                "kanzi": ["最初"],
                "english": ["first", "beginning"],
                "meaning": "최초"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "시작",
                "japanese": ["はじめ", "始め"],
                "hiragana": ["はじめ"],
                "katakana": [],
                "kanzi": ["始め"],
                "english": ["start", "beginning"],
                "meaning": "시작"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "끝",
                "japanese": ["おわり", "終わり"],
                "hiragana": ["おわり"],
                "katakana": [],
                "kanzi": ["終わり"],
                "english": ["end", "finish"],
                "meaning": "끝"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "일어나다",
                "japanese": ["おきる", "起きる"],
                "hiragana": ["おきる"],
                "katakana": [],
                "kanzi": ["起きる"],
                "english": ["to get up"],
                "meaning": "일어나다"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "기다리다",
                "japanese": ["まつ", "待つ"],
                "hiragana": ["まつ"],
                "katakana": [],
                "kanzi": ["待つ"],
                "english": ["to wait"],
                "meaning": "기다리다"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "끝나다",
                "japanese": ["おわる", "終わる"],
                "hiragana": ["おわる"],
                "katakana": [],
                "kanzi": ["終わる"],
                "english": ["to end", "to finish"],
                "meaning": "끝나다"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "곤란하다",
                "japanese": ["こまる", "困る"],
                "hiragana": ["こまる"],
                "katakana": [],
                "kanzi": ["困る"],
                "english": ["to be troubled", "to be in a fix"],
                "meaning": "곤란하다"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "자다",
                "japanese": ["ねる", "寝る"],
                "hiragana": ["ねる"],
                "katakana": [],
                "kanzi": ["寝る"],
                "english": ["to sleep"],
                "meaning": "자다"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "서두르다",
                "japanese": ["いそぐ", "急ぐ"],
                "hiragana": ["いそぐ"],
                "katakana": [],
                "kanzi": ["急ぐ"],
                "english": ["to hurry"],
                "meaning": "서두르다"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "걸리다",
                "japanese": ["かかる", "掛かる"],
                "hiragana": ["かかる"],
                "katakana": [],
                "kanzi": ["掛かる"],
                "english": ["to take (time/money)"],
                "meaning": "걸리다"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "제때에 맞다",
                "japanese": ["まにあう", "間に合う"],
                "hiragana": ["まにあう"],
                "katakana": [],
                "kanzi": ["間に合う"],
                "english": ["to be on time", "to make it"],
                "meaning": "제때에 맞다"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "イ형용사",
                "level": "N5",
                "wordClass": "형용사",
                "korean": "많다",
                "japanese": ["おおい", "多い"],
                "hiragana": ["おおい"],
                "katakana": [],
                "kanzi": ["多い"],
                "english": ["many", "much"],
                "meaning": "많다"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "イ형용사",
                "level": "N5",
                "wordClass": "형용사",
                "korean": "적다",
                "japanese": ["すくない", "少ない"],
                "hiragana": ["すくない"],
                "katakana": [],
                "kanzi": ["少ない"],
                "english": ["few", "little"],
                "meaning": "적다"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "イ형용사",
                "level": "N5",
                "wordClass": "형용사",
                "korean": "이르다",
                "japanese": ["はやい", "早い"],
                "hiragana": ["はやい"],
                "katakana": [],
                "kanzi": ["早い"],
                "english": ["early"],
                "meaning": "이르다"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "イ형용사",
                "level": "N5",
                "wordClass": "형용사",
                "korean": "바쁘다",
                "japanese": ["いそがしい", "忙しい"],
                "hiragana": ["いそがしい"],
                "katakana": [],
                "kanzi": ["忙しい"],
                "english": ["busy"],
                "meaning": "바쁘다"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "イ형용사",
                "level": "N5",
                "wordClass": "형용사",
                "korean": "늦다",
                "japanese": ["おそい", "遅い"],
                "hiragana": ["おそい"],
                "katakana": [],
                "kanzi": ["遅い"],
                "english": ["late"],
                "meaning": "늦다"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "イ형용사",
                "level": "N5",
                "wordClass": "형용사",
                "korean": "길다",
                "japanese": ["ながい", "長い"],
                "hiragana": ["ながい"],
                "katakana": [],
                "kanzi": ["長い"],
                "english": ["long"],
                "meaning": "길다"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "イ형용사",
                "level": "N5",
                "wordClass": "형용사",
                "korean": "짧다",
                "japanese": ["みじかい", "短い"],
                "hiragana": ["みじかい"],
                "katakana": [],
                "kanzi": ["短い"],
                "english": ["short"],
                "meaning": "짧다"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "イ형용사",
                "level": "N5",
                "wordClass": "형용사",
                "korean": "없다",
                "japanese": ["ない", "無い"],
                "hiragana": ["ない"],
                "katakana": [],
                "kanzi": ["無い"],
                "english": ["not exist", "don't have"],
                "meaning": "없다"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "ナ형용사",
                "level": "N5",
                "wordClass": "형용사",
                "korean": "괜찮다",
                "japanese": ["だいじょうぶ", "大丈夫"],
                "hiragana": ["だいじょうぶ"],
                "katakana": [],
                "kanzi": ["大丈夫"],
                "english": ["all right", "okay"],
                "meaning": "괜찮다"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "ナ형용사",
                "level": "N5",
                "wordClass": "형용사",
                "korean": "한가하다",
                "japanese": ["ひま", "暇"],
                "hiragana": ["ひま"],
                "katakana": [],
                "kanzi": ["暇"],
                "english": ["free (time)", "leisurely"],
                "meaning": "한가하다"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "시간 표현",
                "level": "N5",
                "wordClass": "명사",
                "korean": "재작년",
                "japanese": ["おととし", "一昨年"],
                "hiragana": ["おととし"],
                "katakana": [],
                "kanzi": ["一昨年"],
                "english": ["the year before last"],
                "meaning": "재작년"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "시간 표현",
                "level": "N5",
                "wordClass": "명사",
                "korean": "작년",
                "japanese": ["きょねん", "去年"],
                "hiragana": ["きょねん"],
                "katakana": [],
                "kanzi": ["去年"],
                "english": ["last year"],
                "meaning": "작년"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "시간 표현",
                "level": "N5",
                "wordClass": "명사",
                "korean": "올해",
                "japanese": ["ことし", "今年"],
                "hiragana": ["ことし"],
                "katakana": [],
                "kanzi": ["今年"],
                "english": ["this year"],
                "meaning": "올해"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "시간 표현",
                "level": "N5",
                "wordClass": "명사",
                "korean": "내년",
                "japanese": ["らいねん", "来年"],
                "hiragana": ["らいねん"],
                "katakana": [],
                "kanzi": ["来年"],
                "english": ["next year"],
                "meaning": "내년"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "시간 표현",
                "level": "N5",
                "wordClass": "명사",
                "korean": "내후년",
                "japanese": ["さらいねん", "再来年"],
                "hiragana": ["さらいねん"],
                "katakana": [],
                "kanzi": ["再来年"],
                "english": ["the year after next"],
                "meaning": "내후년"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "시간 표현",
                "level": "N5",
                "wordClass": "명사",
                "korean": "지난달",
                "japanese": ["せんげつ", "先月"],
                "hiragana": ["せんげつ"],
                "katakana": [],
                "kanzi": ["先月"],
                "english": ["last month"],
                "meaning": "지난달"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "시간 표현",
                "level": "N5",
                "wordClass": "명사",
                "korean": "이번달",
                "japanese": ["こんげつ", "今月"],
                "hiragana": ["こんげつ"],
                "katakana": [],
                "kanzi": ["今月"],
                "english": ["this month"],
                "meaning": "이번달"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "시간 표현",
                "level": "N5",
                "wordClass": "명사",
                "korean": "다음달",
                "japanese": ["らいげつ", "来月"],
                "hiragana": ["らいげつ"],
                "katakana": [],
                "kanzi": ["来月"],
                "english": ["next month"],
                "meaning": "다음달"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "시간 표현",
                "level": "N5",
                "wordClass": "명사",
                "korean": "다다음달",
                "japanese": ["さらいげつ", "再来月"],
                "hiragana": ["さらいげつ"],
                "katakana": [],
                "kanzi": ["再来月"],
                "english": ["the month after next"],
                "meaning": "다다음달"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "시간 표현",
                "level": "N5",
                "wordClass": "명사",
                "korean": "지난주",
                "japanese": ["せんしゅう", "先週"],
                "hiragana": ["せんしゅう"],
                "katakana": [],
                "kanzi": ["先週"],
                "english": ["last week"],
                "meaning": "지난주"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "시간 표현",
                "level": "N5",
                "wordClass": "명사",
                "korean": "이번주",
                "japanese": ["こんしゅう", "今週"],
                "hiragana": ["こんしゅう"],
                "katakana": [],
                "kanzi": ["今週"],
                "english": ["this week"],
                "meaning": "이번주"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "시간 표현",
                "level": "N5",
                "wordClass": "명사",
                "korean": "다음주",
                "japanese": ["らいしゅう", "来週"],
                "hiragana": ["らいしゅう"],
                "katakana": [],
                "kanzi": ["来週"],
                "english": ["next week"],
                "meaning": "다음주"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "시간 표현",
                "level": "N5",
                "wordClass": "명사",
                "korean": "다다음주",
                "japanese": ["さらいしゅう", "再来週"],
                "hiragana": ["さらいしゅう"],
                "katakana": [],
                "kanzi": ["再来週"],
                "english": ["the week after next"],
                "meaning": "다다음주"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "시간 표현",
                "level": "N5",
                "wordClass": "명사",
                "korean": "그저께",
                "japanese": ["おととい", "一昨日"],
                "hiragana": ["おととい"],
                "katakana": [],
                "kanzi": ["一昨日"],
                "english": ["the day before yesterday"],
                "meaning": "그저께"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "시간 표현",
                "level": "N5",
                "wordClass": "명사",
                "korean": "어제",
                "japanese": ["きのう", "昨日"],
                "hiragana": ["きのう"],
                "katakana": [],
                "kanzi": ["昨日"],
                "english": ["yesterday"],
                "meaning": "어제"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "시간 표현",
                "level": "N5",
                "wordClass": "명사",
                "korean": "오늘",
                "japanese": ["きょう", "今日"],
                "hiragana": ["きょう"],
                "katakana": [],
                "kanzi": ["今日"],
                "english": ["today"],
                "meaning": "오늘"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "시간 표현",
                "level": "N5",
                "wordClass": "명사",
                "korean": "내일",
                "japanese": ["あした", "明日"],
                "hiragana": ["あした"],
                "katakana": [],
                "kanzi": ["明日"],
                "english": ["tomorrow"],
                "meaning": "내일"
            },
            {
                "title": "DAY 3 시간",
                "chapter": "시간 표현",
                "level": "N5",
                "wordClass": "명사",
                "korean": "모레",
                "japanese": ["あさって", "明後日"],
                "hiragana": ["あさって"],
                "katakana": [],
                "kanzi": ["明後日"],
                "english": ["the day after tomorrow"],
                "meaning": "모레"
            }
        ],
        skipDuplicates: true,
    });
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    }); 