import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
    await prisma.word.createMany({
        data: [
            {
                korean: '사람',
                japanese: ['ひと', '人'],
                english: ['person', 'human'],
                meaning: '사람, 인류',
                level: "N5",
            },
            {
                korean: '물',
                japanese: ['みず', '水'],
                english: ['water'],
                meaning: '물',
                level: "N5",
            },
            {
                korean: '불',
                japanese: ['ひ', '火'],
                english: ['fire'],
                meaning: '불',
                level: "N5",
            },
            {
                korean: '하늘',
                japanese: ['そら', '空'],
                english: ['sky'],
                meaning: '하늘',
                level: "N5",
            },
            {
                korean: '산',
                japanese: ['やま', '山'],
                english: ['mountain'],
                meaning: '산',
                level: "N5",
            },
            {
                korean: '나무',
                japanese: ['き', '木'],
                english: ['tree'],
                meaning: '나무',
                level: "N5",
            },
            {
                korean: '집',
                japanese: ['いえ', '家'],
                english: ['house', 'home'],
                meaning: '집',
                level: "N5",
            },
            {
                korean: '책',
                japanese: ['ほん', '本'],
                english: ['book'],
                meaning: '책',
                level: "N5",
            },
            {
                korean: '학교',
                japanese: ['がっこう', '学校'],
                english: ['school'],
                meaning: '학교',
                level: "N5",
            },
            {
                korean: '음식',
                japanese: ['たべもの', '食べ物'],
                english: ['food'],
                meaning: '음식',
                level: "N5",
            },
            {
                korean: '위',
                japanese: ['うえ', '上'],
                english: ['above', 'up'],
                meaning: '위쪽, 위',
                level: "N5",
            },
            {
                korean: '하늘',
                japanese: ['そら', '空'],
                english: ['sky'],
                meaning: '하늘',
                level: "N5",
            },
            {
                korean: '아래',
                japanese: ['した', '下'],
                english: ['below', 'down'],
                meaning: '아래쪽, 밑',
                level: "N5",
            },
            {
                korean: '오른쪽',
                japanese: ['みぎ', '右'],
                english: ['right (direction)'],
                meaning: '오른쪽',
                level: "N5",
            },
            {
                korean: '왼쪽',
                japanese: ['ひだり', '左'],
                english: ['left (direction)'],
                meaning: '왼쪽',
                level: "N5",
            },
            {
                korean: '동쪽',
                japanese: ['ひがし', '東'],
                english: ['east'],
                meaning: '동쪽',
                level: "N5",
            },
            {
                korean: '서쪽',
                japanese: ['にし', '西'],
                english: ['west'],
                meaning: '서쪽',
                level: "N5",
            },
            {
                korean: '남쪽',
                japanese: ['みなみ', '南'],
                english: ['south'],
                meaning: '남쪽',
                level: "N5",
            },
            {
                korean: '북쪽',
                japanese: ['きた', '北'],
                english: ['north'],
                meaning: '북쪽',
                level: "N5",
            },
            {
                korean: '앞',
                japanese: ['まえ', '前'],
                english: ['front'],
                meaning: '앞',
                level: "N5",
            },
            {
                korean: '뒤',
                japanese: ['うしろ', '後ろ'],
                english: ['behind', 'back'],
                meaning: '뒤',
                level: "N5",
            },
            {
                korean: '안',
                japanese: ['なか', '中'],
                english: ['inside'],
                meaning: '안',
                level: "N5",
            },
            {
                korean: '밖',
                japanese: ['そと', '外'],
                english: ['outside'],
                meaning: '밖',
                level: "N5",
            },
            {
                korean: '강',
                japanese: ['かわ', '川'],
                english: ['river'],
                meaning: '강',
                level: "N5",
            },
            {
                korean: '동물',
                japanese: ['どうぶつ', '動物'],
                english: ['animal'],
                meaning: '동물',
                level: "N5",
            },
            {
                korean: '개',
                japanese: ['いぬ', '犬'],
                english: ['dog'],
                meaning: '개',
                level: "N5",
            },
            {
                korean: '고양이',
                japanese: ['ねこ', '猫'],
                english: ['cat'],
                meaning: '고양이',
                level: "N5",
            },
            {
                korean: '사람',
                japanese: ['ひと', '人'],
                english: ['person'],
                meaning: '사람',
                level: "N5",
            },
            {
                korean: '아이',
                japanese: ['こども', '子ども'],
                english: ['child'],
                meaning: '아이',
                level: "N5",
            },
            {
                korean: '남자',
                japanese: ['おとこ', '男'],
                english: ['man'],
                meaning: '남자',
                level: "N5",
            },
            {
                korean: '여자',
                japanese: ['おんな', '女'],
                english: ['woman'],
                meaning: '여자',
                level: "N5",
            },
            {
                korean: '아버지',
                japanese: ['ちち', '父'],
                english: ['father'],
                meaning: '아버지',
                level: "N5",
            },
            {
                korean: '어머니',
                japanese: ['はは', '母'],
                english: ['mother'],
                meaning: '어머니',
                level: "N5",
            },
            {
                korean: '선생님',
                japanese: ['せんせい', '先生'],
                english: ['teacher'],
                meaning: '선생님',
                level: "N5",
            },
            {
                korean: '학생',
                japanese: ['がくせい', '学生'],
                english: ['student'],
                meaning: '학생',
                level: "N5",
            },
            {
                korean: '회사원',
                japanese: ['かいしゃいん', '会社員'],
                english: ['office worker'],
                meaning: '회사원',
                level: "N5",
            },
            {
                korean: '경찰관',
                japanese: ['けいさつかん', '警察官'],
                english: ['police officer'],
                meaning: '경찰관',
                level: "N5",
            },
            {
                korean: '의사',
                japanese: ['いしゃ', '医者'],
                english: ['doctor'],
                meaning: '의사',
                level: "N5",
            },
            {
                korean: '학교',
                japanese: ['がっこう', '学校'],
                english: ['school'],
                meaning: '학교',
                level: "N5",
            },
            {
                korean: '초등학교',
                japanese: ['しょうがっこう', '小学校'],
                english: ['elementary school'],
                meaning: '초등학교',
                level: "N5",
            },
            {
                korean: '중학교',
                japanese: ['ちゅうがっこう', '中学校'],
                english: ['middle school'],
                meaning: '중학교',
                level: "N5",
            },
            {
                korean: '고등학교',
                japanese: ['こうこう', '高校'],
                english: ['high school'],
                meaning: '고등학교',
                level: "N5",
            },
            {
                korean: '대학교',
                japanese: ['だいがく', '大学'],
                english: ['university'],
                meaning: '대학교',
                level: "N5",
            },
            {
                korean: '도서관',
                japanese: ['としょかん', '図書館'],
                english: ['library'],
                meaning: '도서관',
                level: "N5",
            },
            {
                korean: '병원',
                japanese: ['びょういん', '病院'],
                english: ['hospital'],
                meaning: '병원',
                level: "N5",
            },
            {
                korean: '친구',
                japanese: ['ともだち', '友達'],
                english: ['friend'],
                meaning: '친구',
                level: "N5",
            },
            {
                korean: '자동차',
                japanese: ['くるま', '車'],
                english: ['car'],
                meaning: '자동차',
                level: "N5",
            },
            {
                korean: '스마트폰',
                japanese: ['スマホ'],
                english: ['smartphone'],
                meaning: '스마트폰',
                level: "N5",
            },
            {
                korean: '초대하다',
                japanese: ['さそう', '誘う'],
                english: ['invite'],
                meaning: '초대하다',
                level: "N5",
            },
            {
                korean: '오다',
                japanese: ['くる', '来る'],
                english: ['come'],
                meaning: '오다',
                level: "N5",
            },
            {
                korean: '노트북',
                japanese: ['ノートパソコン'],
                english: ['laptop'],
                meaning: '노트북 컴퓨터',
                level: "N5",
            },
            {
                korean: '향수',
                japanese: ['こうすい', '香水'],
                english: ['perfume'],
                meaning: '향수',
                level: "N5",
            },
            {
                korean: '부르다',
                japanese: ['よぶ', '呼ぶ'],
                english: ['call'],
                meaning: '부르다',
                level: "N5",
            },
            {
                korean: '파티를 하다',
                japanese: ['パーティーをする'],
                english: ['have a party'],
                meaning: '파티를 하다',
                level: "N5",
            },
            {
                korean: '깨뜨리다',
                japanese: ['わる', '割る'],
                english: ['break', 'shatter'],
                meaning: '깨뜨리다',
                level: "N5",
            },
            {
                korean: '떨어뜨리다',
                japanese: ['おとす', '落とす'],
                english: ['drop'],
                meaning: '떨어뜨리다',
                level: "N5",
            },
            {
                korean: '길을 잃다',
                japanese: ['みちにまよう', '道に迷う'],
                english: ['get lost'],
                meaning: '길을 잃다',
                level: "N5",
            },
            {
                korean: '틀리다',
                japanese: ['まちがえる', '間違える'],
                english: ['make a mistake', 'be wrong'],
                meaning: '틀리다',
                level: "N5",
            },
            {
                korean: '죽다',
                japanese: ['しぬ', '死ぬ'],
                english: ['die'],
                meaning: '죽다',
                level: "N5",
            },
            {
                korean: '옷',
                japanese: ['ふく'],
                english: ['clothes'],
                meaning: '옷',
                level: "N5",
            },
            {
                korean: '상의',
                japanese: ['うわぎ'],
                english: ['jacket', 'outerwear'],
                meaning: '겉옷, 상의',
                level: "N5",
            },
            {
                korean: '빨간 색',
                japanese: ['あかいろ', '赤色'],
                english: ['red color'],
                meaning: '빨간색',
                level: "N5",
            },
            {
                korean: '하양',
                japanese: ['しろ', '白'],
                english: ['white'],
                meaning: '하얀색',
                level: "N5",
            },
            {
                korean: '파랑',
                japanese: ['あお'],
                english: ['blue'],
                meaning: '파란색',
                level: "N5",
            },
            {
                korean: '검정',
                japanese: ['くろ'],
                english: ['black'],
                meaning: '검정색',
                level: "N5",
            },
            {
                korean: '모자',
                japanese: ['ぼうし'],
                english: ['hat'],
                meaning: '모자',
                level: "N5",
            },
            {
                korean: '(모자를) 쓰다',
                japanese: ['かぶる'],
                english: ['put on (hat)'],
                meaning: '(모자 등을) 쓰다',
                level: "N5",
            },
            {
                korean: '안경',
                japanese: ['めがね'],
                english: ['glasses'],
                meaning: '안경',
                level: "N5",
            },
            {
                korean: '시계',
                japanese: ['とけい'],
                english: ['clock', 'watch'],
                meaning: '시계',
                level: "N5",
            },
            {
                korean: '신발',
                japanese: ['くつ'],
                english: ['shoes'],
                meaning: '신발',
                level: "N5",
            },
            {
                korean: '입다',
                japanese: ['きる', '着る'],
                english: ['wear'],
                meaning: '옷을 입다',
                level: "N5",
            },
            {
                korean: '입다, 신다',
                japanese: ['はく'],
                english: ['put on (shoes, pants)'],
                meaning: '하의나 신발을 입거나 신다',
                level: "N5",
            },
            {
                korean: '이름',
                japanese: ['なまえ'],
                english: ['name'],
                meaning: '이름',
                level: "N5",
            },
            {
                korean: '주소',
                japanese: ['じゅうしょ', '住所'],
                english: ['address'],
                meaning: '주소',
                level: "N5",
            },
            {
                korean: '전화하다',
                japanese: ['でんわする', '電話する'],
                english: ['make a call'],
                meaning: '전화하다',
                level: "N5",
            },
            {
                korean: '쇼핑',
                japanese: ['かいもの', '買い物'],
                english: ['shopping'],
                meaning: '쇼핑, 장보기',
                level: "N5",
            },
            {
                korean: '사다',
                japanese: ['かう', '買う'],
                english: ['buy'],
                meaning: '사다',
                level: "N5",
            },
            {
                korean: '팔다',
                japanese: ['うる', '売る'],
                english: ['sell'],
                meaning: '팔다',
                level: "N5",
            },
            {
                korean: '남자',
                japanese: ['おとこのひと', '男の人'],
                english: ['man'],
                meaning: '남자',
                level: "N5",
            },
            {
                korean: '그',
                japanese: ['かれ', '彼'],
                english: ['he'],
                meaning: '그, 남자',
                level: "N5",
            },
            {
                korean: '전달하다',
                japanese: ['つたえる'],
                english: ['convey', 'communicate'],
                meaning: '전달하다',
                level: "N5",
            },
            {
                korean: '여자',
                japanese: ['おんなのひと', '女の人'],
                english: ['woman'],
                meaning: '여자',
                level: "N5",
            },
            {
                korean: '그녀',
                japanese: ['かのじょ', '彼女'],
                english: ['she'],
                meaning: '그녀',
                level: "N5",
            },
            {
                korean: '친절하다',
                japanese: ['しんせつだ'],
                english: ['kind'],
                meaning: '친절하다',
                level: "N5",
            },
            {
                korean: '아이',
                japanese: ['こども', '子ども'],
                english: ['child'],
                meaning: '아이',
                level: "N5",
            },
            {
                korean: '태어나다',
                japanese: ['うまれる', '生まれる'],
                english: ['be born'],
                meaning: '태어나다',
                level: "N5",
            },
            {
                korean: '지도',
                japanese: ['ちず', '地図'],
                english: ['map'],
                meaning: '지도',
                level: "N5",
            },
            {
                korean: '장소',
                japanese: ['ばしょ', '場所'],
                english: ['place'],
                meaning: '장소',
                level: "N5",
            },
            {
                korean: '역',
                japanese: ['えき', '駅'],
                english: ['station'],
                meaning: '기차역',
                level: "N5",
            },
            {
                korean: '회사',
                japanese: ['かいしゃ', '会社'],
                english: ['company'],
                meaning: '회사',
                level: "N5",
            },
            {
                korean: '은행',
                japanese: ['ぎんこう', '銀行'],
                english: ['bank'],
                meaning: '은행',
                level: "N5",
            },
            {
                korean: '우체국',
                japanese: ['ゆうびんきょく'],
                english: ['post office'],
                meaning: '우체국',
                level: "N5",
            },
            {
                korean: '엽서',
                japanese: ['はがき'],
                english: ['postcard'],
                meaning: '엽서',
                level: "N5",
            },
            {
                korean: '우표',
                japanese: ['きって'],
                english: ['stamp'],
                meaning: '우표',
                level: "N5",
            },
            {
                korean: '편지',
                japanese: ['てがみ', '手紙'],
                english: ['letter'],
                meaning: '편지',
                level: "N5",
            },
            {
                korean: '도착하다',
                japanese: ['つく'],
                english: ['arrive'],
                meaning: '도착하다',
                level: "N5",
            },
            {
                korean: '만나다',
                japanese: ['あう'],
                english: ['meet'],
                meaning: '만나다',
                level: "N5",
            },
            {
                korean: '놀다',
                japanese: ['あそぶ'],
                english: ['play'],
                meaning: '놀다',
                level: "N5",
            },
            {
                korean: '근무하다',
                japanese: ['つとめる'],
                english: ['work'],
                meaning: '근무하다',
                level: "N5",
            },
            {
                korean: '일하다',
                japanese: ['はたらく'],
                english: ['work'],
                meaning: '일하다',
                level: "N5",
            },
            {
                korean: '새롭다',
                japanese: ['あたらしい', '新しい'],
                english: ['new'],
                meaning: '새롭다',
                level: "N5",
            },
            {
                korean: '오래되다',
                japanese: ['ふるい', '古い'],
                english: ['old'],
                meaning: '오래되다',
                level: "N5",
            },
            {
                korean: '높다, 비싸다',
                japanese: ['たかい', '高い'],
                english: ['tall', 'expensive'],
                meaning: '높다, 비싸다',
                level: "N5",
            },
            {
                korean: '낮다',
                japanese: ['ひくい', '低い'],
                english: ['low'],
                meaning: '낮다',
                level: "N5",
            },
            {
                korean: '싸다',
                japanese: ['やすい', '安い'],
                english: ['cheap'],
                meaning: '값이 싸다',
                level: "N5",
            },
            {
                korean: '무겁다',
                japanese: ['おもい', '重い'],
                english: ['heavy'],
                meaning: '무겁다',
                level: "N5",
            },
            {
                korean: '가볍다',
                japanese: ['かるい', '軽い'],
                english: ['light'],
                meaning: '가볍다',
                level: "N5",
            },
            {
                korean: '집',
                japanese: ['いえ', 'うち'],
                english: ['house', 'home'],
                meaning: '집',
                level: "N5",
            },
            {
                korean: '외출하다',
                japanese: ['でかける'],
                english: ['go out'],
                meaning: '외출하다',
                level: "N5",
            },
            {
                korean: '돌아가다',
                japanese: ['かえる', '帰る'],
                english: ['go back', 'return'],
                meaning: '돌아가다',
                level: "N5",
            },
            {
                korean: '음식',
                japanese: ['たべもの', '食べ物'],
                english: ['food'],
                meaning: '음식',
                level: "N5",
            },
            {
                korean: '식사',
                japanese: ['しょくじ', '食事'],
                english: ['meal'],
                meaning: '식사',
                level: "N5",
            },
            {
                korean: '밥',
                japanese: ['ごはん', 'ご飯'],
                english: ['rice', 'meal'],
                meaning: '밥, 식사',
                level: "N5",
            },
            {
                korean: '고기',
                japanese: ['にく', '肉'],
                english: ['meat'],
                meaning: '고기',
                level: "N5",
            },
            {
                korean: '생선',
                japanese: ['さかな', '魚'],
                english: ['fish'],
                meaning: '생선',
                level: "N5",
            },
            {
                korean: '음료',
                japanese: ['のみもの', '飲み物'],
                english: ['drink', 'beverage'],
                meaning: '음료',
                level: "N5",
            },
            {
                korean: '야채',
                japanese: ['やさい', '野菜'],
                english: ['vegetable'],
                meaning: '채소, 야채',
                level: "N5",
            },
            {
                korean: '과일',
                japanese: ['くだもの', '果物'],
                english: ['fruit'],
                meaning: '과일',
                level: "N5",
            },
            {
                korean: '반, 절반',
                japanese: ['はんぶん', '半分'],
                english: ['half'],
                meaning: '절반',
                level: "N5",
            },
            {
                korean: '요리하다',
                japanese: ['りょうりする'],
                english: ['cook'],
                meaning: '요리하다',
                level: "N5",
            },
            {
                korean: '설탕',
                japanese: ['さとう'],
                english: ['sugar'],
                meaning: '설탕',
                level: "N5",
            },
            {
                korean: '소금',
                japanese: ['しお'],
                english: ['salt'],
                meaning: '소금',
                level: "N5",
            },
            {
                korean: '주문',
                japanese: ['ちゅうもん', '注文'],
                english: ['order'],
                meaning: '주문하다',
                level: "N5",
            },
            {
                korean: '씻다',
                japanese: ['あらう', '洗う'],
                english: ['wash'],
                meaning: '씻다',
                level: "N5",
            },
            {
                korean: '사용하다',
                japanese: ['つかう', '使う'],
                english: ['use'],
                meaning: '사용하다',
                level: "N5",
            },
            {
                korean: '자르다',
                japanese: ['きる', '切る'],
                english: ['cut'],
                meaning: '자르다',
                level: "N5",
            },
            {
                korean: '뜨겁다',
                japanese: ['あつい'],
                english: ['hot'],
                meaning: '뜨겁다',
                level: "N5",
            },
            {
                korean: '차갑다',
                japanese: ['つめたい'],
                english: ['cold'],
                meaning: '차갑다',
                level: "N5",
            },
            {
                korean: '두껍다',
                japanese: ['あつい'],
                english: ['thick'],
                meaning: '두껍다',
                level: "N5",
            },
            {
                korean: '얇다',
                japanese: ['うすい'],
                english: ['thin'],
                meaning: '얇다',
                level: "N5",
            },
            {
                korean: '몸',
                japanese: ['からだ', '体'],
                english: ['body'],
                meaning: '몸',
                level: "N5",
            },
            {
                korean: '머리',
                japanese: ['あたま', '頭'],
                english: ['head'],
                meaning: '머리',
                level: "N5",
            },
            {
                korean: '귀',
                japanese: ['みみ', '耳'],
                english: ['ear'],
                meaning: '귀',
                level: "N5",
            },
            {
                korean: '손',
                japanese: ['て', '手'],
                english: ['hand'],
                meaning: '손',
                level: "N5",
            },
            {
                korean: '배',
                japanese: ['おなか'],
                english: ['stomach'],
                meaning: '배',
                level: "N5",
            },
            {
                korean: '발',
                japanese: ['あし', '足'],
                english: ['foot', 'leg'],
                meaning: '발, 다리',
                level: "N5",
            },
            {
                korean: '눈',
                japanese: ['め', '目'],
                english: ['eye'],
                meaning: '눈',
                level: "N5",
            },
            {
                korean: '코',
                japanese: ['はな'],
                english: ['nose'],
                meaning: '코',
                level: "N5",
            },
            {
                korean: '입',
                japanese: ['くち', '口'],
                english: ['mouth'],
                meaning: '입',
                level: "N5",
            },
            {
                korean: '이, 치아',
                japanese: ['は'],
                english: ['tooth'],
                meaning: '이, 치아',
                level: "N5",
            },
            {
                korean: '지치다',
                japanese: ['つかれた'],
                english: ['tired'],
                meaning: '피곤하다, 지치다',
                level: "N5",
            },
            {
                korean: '(담배) 피우다, 들이마시다',
                japanese: ['すう'],
                english: ['smoke', 'inhale'],
                meaning: '흡입하다, 피우다',
                level: "N5",
            },
            {
                korean: '(샤워를) 하다, 뒤집어쓰다',
                japanese: ['あびる'],
                english: ['bathe', 'pour on oneself'],
                meaning: '샤워하다, 뒤집어쓰다',
                level: "N5",
            },
            {
                korean: '강하다',
                japanese: ['つよい'],
                english: ['strong'],
                meaning: '강하다',
                level: "N5",
            },
            {
                korean: '건강하다',
                japanese: ['げんきだ'],
                english: ['healthy'],
                meaning: '건강하다',
                level: "N5",
            },
            {
                korean: '두껍다',
                japanese: ['ふとい'],
                english: ['thick'],
                meaning: '두껍다',
                level: "N5",
            },
            {
                korean: '약하다',
                japanese: ['よわい'],
                english: ['weak'],
                meaning: '약하다',
                level: "N5",
            },
            {
                korean: '힘들다',
                japanese: ['たいへんだ'],
                english: ['hard', 'tough'],
                meaning: '힘들다',
                level: "N5",
            },
            {
                korean: '얇다',
                japanese: ['ほそい'],
                english: ['thin'],
                meaning: '얇다',
                level: "N5",
            },
            {
                korean: '언제',
                japanese: ['いつ'],
                english: ['when'],
                meaning: '언제',
                level: "N5",
            },
            {
                korean: '어떻게',
                japanese: ['どう'],
                english: ['how'],
                meaning: '어떻게',
                level: "N5",
            },
            {
                korean: '어떻게 해서',
                japanese: ['どうやって'],
                english: ['by what means'],
                meaning: '어떻게 해서',
                level: "N5",
            },
            {
                korean: '어째서, 왜',
                japanese: ['どうして'],
                english: ['why'],
                meaning: '왜, 어째서',
                level: "N5",
            },
            {
                korean: '노래',
                japanese: ['うた', '歌'],
                english: ['song'],
                meaning: '노래',
                level: "N5",
            },
            {
                korean: '그림',
                japanese: ['え'],
                english: ['picture', 'drawing'],
                meaning: '그림',
                level: "N5",
            },
            {
                korean: '연습',
                japanese: ['れんしゅう'],
                english: ['practice'],
                meaning: '연습',
                level: "N5",
            },
            {
                korean: '이야기',
                japanese: ['はなし', '話'],
                english: ['story', 'talk'],
                meaning: '이야기',
                level: "N5",
            },
            {
                korean: '일',
                japanese: ['しごと'],
                english: ['work', 'job'],
                meaning: '일',
                level: "N5",
            },
            {
                korean: '회의하다',
                japanese: ['かいぎする'],
                english: ['have a meeting'],
                meaning: '회의하다',
                level: "N5",
            },
            {
                korean: '연구',
                japanese: ['けんきゅう'],
                english: ['research'],
                meaning: '연구',
                level: "N5",
            },
            {
                korean: '여행하다',
                japanese: ['りょこうする', '旅行する'],
                english: ['travel'],
                meaning: '여행하다',
                level: "N5",
            },
            {
                korean: '달리다',
                japanese: ['はしる'],
                english: ['run'],
                meaning: '달리다',
                level: "N5",
            },
            {
                korean: '수영하다',
                japanese: ['およぐ'],
                english: ['swim'],
                meaning: '수영하다',
                level: "N5",
            },
            {
                korean: '아직',
                japanese: ['まだ'],
                english: ['still', 'yet'],
                meaning: '아직',
                level: "N5",
            },
            {
                korean: '또',
                japanese: ['また'],
                english: ['again'],
                meaning: '또',
                level: "N5",
            },
            {
                korean: '더, 좀 더',
                japanese: ['もっと'],
                english: ['more'],
                meaning: '더 많이',
                level: "N5",
            },
            {
                korean: '그러나, 그렇지만',
                japanese: ['しかし'],
                english: ['however'],
                meaning: '그렇지만',
                level: "N5",
            },
            {
                korean: '그래도',
                japanese: ['でも'],
                english: ['but still'],
                meaning: '그래도',
                level: "N5",
            },
            {
                korean: '그래서',
                japanese: ['それで'],
                english: ['so', 'then'],
                meaning: '그래서',
                level: "N5",
            },
            {
                korean: '그러니까',
                japanese: ['だから'],
                english: ['therefore'],
                meaning: '그러니까',
                level: "N5",
            },
            {
                korean: '그리고',
                japanese: ['そして'],
                english: ['and then'],
                meaning: '그리고',
                level: "N5",
            },
            {
                korean: '그리고 나서',
                japanese: ['それから'],
                english: ['after that'],
                meaning: '그런 다음에',
                level: "N5",
            },
            {
                korean: '외국',
                japanese: ['がいこく', '外国'],
                english: ['foreign country'],
                meaning: '외국',
                level: "N5",
            },
            {
                korean: '아시아',
                japanese: ['アジア'],
                english: ['Asia'],
                meaning: '아시아',
                level: "N5",
            },
            {
                korean: '전철',
                japanese: ['でんしゃ', '電車'],
                english: ['train'],
                meaning: '전철',
                level: "N5",
            },
            {
                korean: '자전거',
                japanese: ['じてんしゃ', '自転車'],
                english: ['bicycle'],
                meaning: '자전거',
                level: "N5",
            },
            {
                korean: '어서 오십시오',
                japanese: ['いらっしゃいませ'],
                english: ['Welcome'],
                meaning: '환영 인사',
                level: "N5",
            },
            {
                korean: '어떻습니까?',
                japanese: ['いかがですか'],
                english: ['How is it?'],
                meaning: '상대의 상태를 물을 때',
                level: "N5",
            },
            {
                korean: '잘 먹겠습니다',
                japanese: ['いただきます'],
                english: ['I will eat well'],
                meaning: '식사 전 인사말',
                level: "N5",
            },
            {
                korean: '잘 먹었습니다',
                japanese: ['ごちそうさまでした'],
                english: ['Thank you for the meal'],
                meaning: '식사 후 인사말',
                level: "N5",
            },
            {
                korean: '다녀오겠습니다',
                japanese: ['いってきます'],
                english: ["I'll go and come back"],
                meaning: '외출할 때 인사',
                level: "N5",
            },
            {
                korean: '다녀오세요',
                japanese: ['いってらっしゃい'],
                english: ['Have a good day'],
                meaning: '배웅할 때 인사',
                level: "N5",
            },
            {
                korean: '다녀왔습니다',
                japanese: ['ただいま'],
                english: ["I'm home"],
                meaning: '귀가 인사',
                level: "N5",
            },
            {
                korean: '어서 와요',
                japanese: ['おかえりなさい'],
                english: ['Welcome back'],
                meaning: '귀가 인사에 대한 답',
                level: "N5",
            },
            {
                korean: '미안해요, 죄송해요',
                japanese: ['ごめんなさい'],
                english: ['sorry'],
                meaning: '사과',
                level: "N5",
            },
            {
                korean: '계세요? 실례하겠습니다',
                japanese: ['ごめんください'],
                english: ['Excuse me', 'May I come in?'],
                meaning: '방문 시 인사',
                level: "N5",
            },
            {
                korean: '밝지 않다',
                japanese: ['あかるくない'],
                english: ['not bright'],
                meaning: '어둡다',
                level: "N5",
            },
            {
                korean: '태어난 날',
                japanese: ['うまれた ひ'],
                english: ['birthday', 'birth date'],
                meaning: '출생일',
                level: "N5",
            },
            {
                korean: '젓가락을 늘어놓다',
                japanese: ['はしを ならべる'],
                english: ['set the chopsticks'],
                meaning: '젓가락을 늘어놓다',
                level: "N5",
            },
            {
                korean: '아파트',
                japanese: ['あぱーと', 'アパート'],
                english: ['apartment'],
                meaning: '아파트',
                level: "N5",
            },
            {
                korean: '아르바이트',
                japanese: ['あるばいと', 'アルバイト'],
                english: ['part-time job'],
                meaning: '아르바이트',
                level: "N5",
            },
            {
                korean: '엘리베이터',
                japanese: ['えれべーたー', 'エレベーター'],
                english: ['elevator'],
                meaning: '엘리베이터',
                level: "N5",
            },
            {
                korean: '컵',
                japanese: ['かっぷ', 'カップ'],
                english: ['cup'],
                meaning: '컵',
                level: "N5",
            },
            {
                korean: '카메라',
                japanese: ['かめら', 'カメラ'],
                english: ['camera'],
                meaning: '카메라',
                level: "N5",
            },
            {
                korean: '카레',
                japanese: ['かれー', 'カレー'],
                english: ['curry'],
                meaning: '카레',
                level: "N5",
            },
            {
                korean: '클래스, 반',
                japanese: ['くらす', 'クラス'],
                english: ['class'],
                meaning: '반, 수업',
                level: "N5",
            },
            {
                korean: '케이크',
                japanese: ['けーき', 'ケーキ'],
                english: ['cake'],
                meaning: '케이크',
                level: "N5",
            },
            {
                korean: '휴대폰',
                japanese: ['けーたい', 'ケータイ'],
                english: ['mobile phone'],
                meaning: '휴대전화',
                level: "N5",
            },
            {
                korean: '커피',
                japanese: ['こーひー', 'コーヒー'],
                english: ['coffee'],
                meaning: '커피',
                level: "N5",
            },
            {
                korean: '복사',
                japanese: ['こぴー', 'コピー'],
                english: ['copy'],
                meaning: '복사',
                level: "N5",
            },
            {
                korean: '편의점',
                japanese: ['こんびに', 'コンビニ'],
                english: ['convenience store'],
                meaning: '편의점',
                level: "N5",
            },
            {
                korean: '축구',
                japanese: ['さっかー', 'サッカー'],
                english: ['soccer'],
                meaning: '축구',
                level: "N5",
            },
            {
                korean: '주스',
                japanese: ['じゅーす', 'ジュース'],
                english: ['juice'],
                meaning: '주스',
                level: "N5",
            },
            {
                korean: '스포츠',
                japanese: ['すぽーつ', 'スポーツ'],
                english: ['sports'],
                meaning: '스포츠',
                level: "N5",
            },
            {
                korean: '바지',
                japanese: ['ずぼん', 'ズボン'],
                english: ['pants'],
                meaning: '바지',
                level: "N5",
            },
            {
                korean: '스마트폰',
                japanese: ['すまほ', 'スマホ'],
                english: ['smartphone'],
                meaning: '스마트폰',
                level: "N5",
            },
            {
                korean: '치즈',
                japanese: ['ちーず', 'チーズ'],
                english: ['cheese'],
                meaning: '치즈',
                level: "N5",
            },
            {
                korean: '초콜릿',
                japanese: ['ちょこれーと', 'チョコレート'],
                english: ['chocolate'],
                meaning: '초콜릿',
                level: "N5",
            },
            {
                korean: '백화점',
                japanese: ['でぱーと', 'デパート'],
                english: ['department store'],
                meaning: '백화점',
                level: "N5",
            },
            {
                korean: '화장실',
                japanese: ['といれ', 'トイレ'],
                english: ['toilet'],
                meaning: '화장실',
                level: "N5",
            },
            {
                korean: '노트',
                japanese: ['のーと', 'ノート'],
                english: ['notebook'],
                meaning: '노트',
                level: "N5",
            },
            {
                korean: '버스',
                japanese: ['ばす', 'バス'],
                english: ['bus'],
                meaning: '버스',
                level: "N5",
            },
            {
                korean: '컴퓨터',
                japanese: ['ぱそこん', 'パソコン'],
                english: ['computer'],
                meaning: '컴퓨터',
                level: "N5",
            },
            {
                korean: '맥주',
                japanese: ['びーる', 'ビール'],
                english: ['beer'],
                meaning: '맥주',
                level: "N5",
            },
            {
                korean: '건물',
                japanese: ['びる', 'ビル'],
                english: ['building'],
                meaning: '건물',
                level: "N5",
            },
            {
                korean: '수영장',
                japanese: ['ぷーる', 'プール'],
                english: ['pool'],
                meaning: '수영장',
                level: "N5",
            },
            {
                korean: '페이지',
                japanese: ['ぺーじ', 'ページ'],
                english: ['page'],
                meaning: '페이지',
                level: "N5",
            },
            {
                korean: '침대',
                japanese: ['べっど', 'ベッド'],
                english: ['bed'],
                meaning: '침대',
                level: "N5",
            },
            {
                korean: '반려동물',
                japanese: ['ぺっと', 'ペット'],
                english: ['pet'],
                meaning: '애완동물',
                level: "N5",
            },
            {
                korean: '메뉴',
                japanese: ['めにゅー', 'メニュー'],
                english: ['menu'],
                meaning: '메뉴',
                level: "N5",
            },
            {
                korean: '레스토랑',
                japanese: ['れすとらん', 'レストラン'],
                english: ['restaurant'],
                meaning: '레스토랑',
                level: "N5",
            },
            {
                korean: '와이셔츠',
                japanese: ['わいしゃつ', 'ワイシャツ'],
                english: ['dress shirt'],
                meaning: '와이셔츠',
                level: "N5",
            },
            {
                korean: '언니, 누나',
                japanese: ['あね', '姉'],
                english: ['older sister'],
                meaning: '언니, 누나',
                level: "N5",
            },
            {
                korean: '오빠, 형',
                japanese: ['あに', '兄'],
                english: ['older brother'],
                meaning: '오빠, 형',
                level: "N5",
            },
            {
                korean: '가을',
                japanese: ['あき', '秋'],
                english: ['autumn'],
                meaning: '가을',
                level: "N5",
            },
            {
                korean: '비',
                japanese: ['あめ', '雨'],
                english: ['rain'],
                meaning: '비',
                level: "N5",
            },
            {
                korean: '마시다',
                japanese: ['のむ', '飲む'],
                english: ['drink'],
                meaning: '마시다',
                level: "N5",
            },
            {
                korean: '먹다',
                japanese: ['たべる', '食べる'],
                english: ['eat'],
                meaning: '먹다',
                level: "N5",
            },
            {
                korean: '100명',
                japanese: ['ひゃくにん', '百人'],
                english: ['100 people'],
                meaning: '100명',
                level: "N5",
            },
            {
                korean: '1명',
                japanese: ['ひとり', '一人'],
                english: ['one person'],
                meaning: '한 사람',
                level: "N5",
            },
            {
                korean: '2명',
                japanese: ['ふたり', '二人'],
                english: ['two people'],
                meaning: '두 사람',
                level: "N5",
            },
            {
                korean: '이름',
                japanese: ['なまえ', '名前'],
                english: ['name'],
                meaning: '이름',
                level: "N5",
            },
            {
                korean: '매일',
                japanese: ['まいにち', '毎日'],
                english: ['every day'],
                meaning: '매일',
                level: "N5",
            },
            {
                korean: '일요일',
                japanese: ['にちようび', '日よう日'],
                english: ['Sunday'],
                meaning: '일요일',
                level: "N5",
            },
            {
                korean: '눈',
                japanese: ['め', '目'],
                english: ['eye'],
                meaning: '눈',
                level: "N5",
            },
            {
                korean: '코',
                japanese: ['はな'],
                english: ['nose'],
                meaning: '코',
                level: "N5",
            },
            {
                korean: '귀',
                japanese: ['みみ'],
                english: ['ear'],
                meaning: '귀',
                level: "N5",
            },
            {
                korean: '목, 목구멍',
                japanese: ['のど'],
                english: ['throat'],
                meaning: '목, 목구멍',
                level: "N5",
            },
            {
                korean: '깊다',
                japanese: ['ふかい'],
                english: ['deep'],
                meaning: '깊다',
                level: "N5",
            },
            {
                korean: '넓다',
                japanese: ['ひろい'],
                english: ['wide'],
                meaning: '넓다',
                level: "N5",
            },
            {
                korean: '좁다',
                japanese: ['せまい'],
                english: ['narrow'],
                meaning: '좁다',
                level: "N5",
            },
            {
                korean: '무겁다',
                japanese: ['おもい'],
                english: ['heavy'],
                meaning: '무겁다',
                level: "N5",
            },
            {
                korean: '들어가다',
                japanese: ['はいる', '入る'],
                english: ['enter'],
                meaning: '들어가다',
                level: "N5",
            },
            {
                korean: '넣다',
                japanese: ['いれる', '入れる'],
                english: ['put in'],
                meaning: '넣다',
                level: "N5",
            },
            {
                korean: '아래',
                japanese: ['した', '下'],
                english: ['below'],
                meaning: '아래',
                level: "N5",
            },
            {
                korean: '안 (공간)',
                japanese: ['なか', '中'],
                english: ['inside'],
                meaning: '안',
                level: "N5",
            },
            {
                korean: '위',
                japanese: ['うえ', '上'],
                english: ['above'],
                meaning: '위',
                level: "N5",
            },
            {
                korean: '옆',
                japanese: ['よこ'],
                english: ['side'],
                meaning: '옆',
                level: "N5",
            },
            {
                korean: '연못',
                japanese: ['いけ'],
                english: ['pond'],
                meaning: '연못',
                level: "N5",
            },
            {
                korean: '강',
                japanese: ['かわ', '川'],
                english: ['river'],
                meaning: '강',
                level: "N5",
            },
            {
                korean: '바다',
                japanese: ['うみ', '海'],
                english: ['sea'],
                meaning: '바다',
                level: "N5",
            },
            {
                korean: '산',
                japanese: ['やま', '山'],
                english: ['mountain'],
                meaning: '산',
                level: "N5",
            },
            {
                korean: '수요일',
                japanese: ['すいようび', '水よう日'],
                english: ['Wednesday'],
                meaning: '수요일',
                level: "N5",
            },
            {
                korean: '토요일',
                japanese: ['どようび', '土よう日'],
                english: ['Saturday'],
                meaning: '토요일',
                level: "N5",
            },
            {
                korean: '1000엔',
                japanese: ['せんえん', '千円'],
                english: ['1000 yen'],
                meaning: '천 엔',
                level: "N5",
            },
            {
                korean: '10000엔',
                japanese: ['いちまんえん', '一万円'],
                english: ['10,000 yen'],
                meaning: '만 엔',
                level: "N5",
            }


        ],
        skipDuplicates: true,
    });
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    }); 