import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
    await prisma.word.createMany({
        data: [
            {
                "title": "DAY 1 위치",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "위",
                "japanese": ["うえ", "上"],
                "hiragana": ["うえ"],
                "katakana": [],
                "kanzi": ["上"],
                "english": ["up", "above"],
                "meaning": "위"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "아래",
                "japanese": ["した", "下"],
                "hiragana": ["した"],
                "katakana": [],
                "kanzi": ["下"],
                "english": ["down", "below"],
                "meaning": "아래"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "왼쪽",
                "japanese": ["ひだり", "左"],
                "hiragana": ["ひだり"],
                "katakana": [],
                "kanzi": ["左"],
                "english": ["left"],
                "meaning": "왼쪽"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "오른쪽",
                "japanese": ["みぎ", "右"],
                "hiragana": ["みぎ"],
                "katakana": [],
                "kanzi": ["右"],
                "english": ["right"],
                "meaning": "오른쪽"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "앞",
                "japanese": ["まえ", "前"],
                "hiragana": ["まえ"],
                "katakana": [],
                "kanzi": ["前"],
                "english": ["front", "before"],
                "meaning": "앞"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "뒤",
                "japanese": ["うしろ", "後ろ"],
                "hiragana": ["うしろ"],
                "katakana": [],
                "kanzi": ["後ろ"],
                "english": ["back", "behind"],
                "meaning": "뒤"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "사이",
                "japanese": ["あいだ", "間"],
                "hiragana": ["あいだ"],
                "katakana": [],
                "kanzi": ["間"],
                "english": ["between", "among"],
                "meaning": "사이"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "근처",
                "japanese": ["ちかく", "近く"],
                "hiragana": ["ちかく"],
                "katakana": [],
                "kanzi": ["近く"],
                "english": ["near", "close"],
                "meaning": "근처"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "근처, 부근",
                "japanese": ["へん", "辺"],
                "hiragana": ["へん"],
                "katakana": [],
                "kanzi": ["辺"],
                "english": ["vicinity", "area"],
                "meaning": "근처, 부근"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "저쪽, 맞은편",
                "japanese": ["むこう", "向こう"],
                "hiragana": ["むこう"],
                "katakana": [],
                "kanzi": ["向こう"],
                "english": ["over there", "opposite side"],
                "meaning": "저쪽, 맞은편"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "동쪽",
                "japanese": ["ひがし", "東"],
                "hiragana": ["ひがし"],
                "katakana": [],
                "kanzi": ["東"],
                "english": ["east"],
                "meaning": "동쪽"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "서쪽",
                "japanese": ["にし", "西"],
                "hiragana": ["にし"],
                "katakana": [],
                "kanzi": ["西"],
                "english": ["west"],
                "meaning": "서쪽"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "남쪽",
                "japanese": ["みなみ", "南"],
                "hiragana": ["みなみ"],
                "katakana": [],
                "kanzi": ["南"],
                "english": ["south"],
                "meaning": "남쪽"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "북쪽",
                "japanese": ["きた", "北"],
                "hiragana": ["きた"],
                "katakana": [],
                "kanzi": ["北"],
                "english": ["north"],
                "meaning": "북쪽"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "밖",
                "japanese": ["そと", "外"],
                "hiragana": ["そと"],
                "katakana": [],
                "kanzi": ["外"],
                "english": ["outside"],
                "meaning": "밖"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "안",
                "japanese": ["なか", "中"],
                "hiragana": ["なか"],
                "katakana": [],
                "kanzi": ["中"],
                "english": ["inside"],
                "meaning": "안"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "모퉁이",
                "japanese": ["かど", "角"],
                "hiragana": ["かど"],
                "katakana": [],
                "kanzi": ["角"],
                "english": ["corner"],
                "meaning": "모퉁이"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "옆, 이웃",
                "japanese": ["となり", "隣"],
                "hiragana": ["となり"],
                "katakana": [],
                "kanzi": ["隣"],
                "english": ["next to", "neighbor"],
                "meaning": "옆, 이웃"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "옆, 가로",
                "japanese": ["よこ", "横"],
                "hiragana": ["よこ"],
                "katakana": [],
                "kanzi": ["横"],
                "english": ["side", "horizontal"],
                "meaning": "옆, 가로"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "명사",
                "level": "N5",
                "wordClass": "명사",
                "korean": "방면, 방향, 쪽",
                "japanese": ["ほう", "方"],
                "hiragana": ["ほう"],
                "katakana": [],
                "kanzi": ["方"],
                "english": ["direction", "way", "side"],
                "meaning": "방면, 방향, 쪽"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "걷다",
                "japanese": ["あるく", "歩く"],
                "hiragana": ["あるく"],
                "katakana": [],
                "kanzi": ["歩く"],
                "english": ["to walk"],
                "meaning": "걷다"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "앉다",
                "japanese": ["すわる", "座る"],
                "hiragana": ["すわる"],
                "katakana": [],
                "kanzi": ["座る"],
                "english": ["to sit"],
                "meaning": "앉다"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "놓다, 두다",
                "japanese": ["おく", "置く"],
                "hiragana": ["おく"],
                "katakana": [],
                "kanzi": ["置く"],
                "english": ["to put", "to place"],
                "meaning": "놓다, 두다"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "붙이다",
                "japanese": ["はる", "貼る"],
                "hiragana": ["はる"],
                "katakana": [],
                "kanzi": ["貼る"],
                "english": ["to stick", "to paste"],
                "meaning": "붙이다"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "서다",
                "japanese": ["たつ", "立つ"],
                "hiragana": ["たつ"],
                "katakana": [],
                "kanzi": ["立つ"],
                "english": ["to stand"],
                "meaning": "서다"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "살다",
                "japanese": ["すむ", "住む"],
                "hiragana": ["すむ"],
                "katakana": [],
                "kanzi": ["住む"],
                "english": ["to live"],
                "meaning": "살다"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "돌다, 방향을 바꾸다",
                "japanese": ["まがる", "曲がる"],
                "hiragana": ["まがる"],
                "katakana": [],
                "kanzi": ["曲がる"],
                "english": ["to turn", "to bend"],
                "meaning": "돌다, 방향을 바꾸다"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "동사",
                "level": "N5",
                "wordClass": "동사",
                "korean": "틀리다, 다르다",
                "japanese": ["ちがう", "違う"],
                "hiragana": ["ちがう"],
                "katakana": [],
                "kanzi": ["違う"],
                "english": ["to be different", "to be wrong"],
                "meaning": "틀리다, 다르다"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "イ형용사",
                "level": "N5",
                "wordClass": "형용사",
                "korean": "가깝다",
                "japanese": ["ちかい", "近い"],
                "hiragana": ["ちかい"],
                "katakana": [],
                "kanzi": ["近い"],
                "english": ["close", "near"],
                "meaning": "가깝다"
            },
            {
                "title": "DAY 1 위치",
                "chapter": "イ형용사",
                "level": "N5",
                "wordClass": "형용사",
                "korean": "멀다",
                "japanese": ["とおい", "遠い"],
                "hiragana": ["とおい"],
                "katakana": [],
                "kanzi": ["遠い"],
                "english": ["far", "distant"],
                "meaning": "멀다"
            },
            {
                "title": "DAY 1 날짜",
                "chapter": "월(月)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "1월",
                "japanese": ["いちがつ", "一月"],
                "hiragana": ["いちがつ"],
                "katakana": [],
                "kanzi": ["一月"],
                "english": ["January"],
                "meaning": "1월"
            },
            {
                "title": "DAY 1 날짜",
                "chapter": "월(月)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "2월",
                "japanese": ["にがつ", "二月"],
                "hiragana": ["にがつ"],
                "katakana": [],
                "kanzi": ["二月"],
                "english": ["February"],
                "meaning": "2월"
            },
            {
                "title": "DAY 1 날짜",
                "chapter": "월(月)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "3월",
                "japanese": ["さんがつ", "三月"],
                "hiragana": ["さんがつ"],
                "katakana": [],
                "kanzi": ["三月"],
                "english": ["March"],
                "meaning": "3월"
            },
            {
                "title": "DAY 1 날짜",
                "chapter": "월(月)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "4월",
                "japanese": ["しがつ", "四月"],
                "hiragana": ["しがつ"],
                "katakana": [],
                "kanzi": ["四月"],
                "english": ["April"],
                "meaning": "4월"
            },
            {
                "title": "DAY 1 날짜",
                "chapter": "월(月)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "5월",
                "japanese": ["ごがつ", "五月"],
                "hiragana": ["ごがつ"],
                "katakana": [],
                "kanzi": ["五月"],
                "english": ["May"],
                "meaning": "5월"
            },
            {
                "title": "DAY 1 날짜",
                "chapter": "월(月)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "6월",
                "japanese": ["ろくがつ", "六月"],
                "hiragana": ["ろくがつ"],
                "katakana": [],
                "kanzi": ["六月"],
                "english": ["June"],
                "meaning": "6월"
            },
            {
                "title": "DAY 1 날짜",
                "chapter": "월(月)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "7월",
                "japanese": ["しちがつ", "七月"],
                "hiragana": ["しちがつ"],
                "katakana": [],
                "kanzi": ["七月"],
                "english": ["July"],
                "meaning": "7월"
            },
            {
                "title": "DAY 1 날짜",
                "chapter": "월(月)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "8월",
                "japanese": ["はちがつ", "八月"],
                "hiragana": ["はちがつ"],
                "katakana": [],
                "kanzi": ["八月"],
                "english": ["August"],
                "meaning": "8월"
            },
            {
                "title": "DAY 1 날짜",
                "chapter": "월(月)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "9월",
                "japanese": ["くがつ", "九月"],
                "hiragana": ["くがつ"],
                "katakana": [],
                "kanzi": ["九月"],
                "english": ["September"],
                "meaning": "9월"
            },
            {
                "title": "DAY 1 날짜",
                "chapter": "월(月)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "10월",
                "japanese": ["じゅうがつ", "十月"],
                "hiragana": ["じゅうがつ"],
                "katakana": [],
                "kanzi": ["十月"],
                "english": ["October"],
                "meaning": "10월"
            },
            {
                "title": "DAY 1 날짜",
                "chapter": "월(月)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "11월",
                "japanese": ["じゅういちがつ", "十一月"],
                "hiragana": ["じゅういちがつ"],
                "katakana": [],
                "kanzi": ["十一月"],
                "english": ["November"],
                "meaning": "11월"
            },
            {
                "title": "DAY 1 날짜",
                "chapter": "월(月)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "12월",
                "japanese": ["じゅうにがつ", "十二月"],
                "hiragana": ["じゅうにがつ"],
                "katakana": [],
                "kanzi": ["十二月"],
                "english": ["December"],
                "meaning": "12월"
            },
            {
                "title": "DAY 1 날짜",
                "chapter": "월(月)",
                "level": "N5",
                "wordClass": "명사",
                "korean": "몇 월",
                "japanese": ["なんがつ", "何月"],
                "hiragana": ["なんがつ"],
                "katakana": [],
                "kanzi": ["何月"],
                "english": ["which month"],
                "meaning": "몇 월"
            },
            {
                "title": "DAY 1 날짜",
                "chapter": "요일",
                "level": "N5",
                "wordClass": "명사",
                "korean": "월요일",
                "japanese": ["げつようび", "月よう日"],
                "hiragana": ["げつようび"],
                "katakana": [],
                "kanzi": ["月曜日"],
                "english": ["Monday"],
                "meaning": "월요일"
            },
            {
                "title": "DAY 1 날짜",
                "chapter": "요일",
                "level": "N5",
                "wordClass": "명사",
                "korean": "화요일",
                "japanese": ["かようび", "火よう日"],
                "hiragana": ["かようび"],
                "katakana": [],
                "kanzi": ["火曜日"],
                "english": ["Tuesday"],
                "meaning": "화요일"
            },
            {
                "title": "DAY 1 날짜",
                "chapter": "요일",
                "level": "N5",
                "wordClass": "명사",
                "korean": "수요일",
                "japanese": ["すいようび", "水よう日"],
                "hiragana": ["すいようび"],
                "katakana": [],
                "kanzi": ["水曜日"],
                "english": ["Wednesday"],
                "meaning": "수요일"
            },
            {
                "title": "DAY 1 날짜",
                "chapter": "요일",
                "level": "N5",
                "wordClass": "명사",
                "korean": "목요일",
                "japanese": ["もくようび", "木よう日"],
                "hiragana": ["もくようび"],
                "katakana": [],
                "kanzi": ["木曜日"],
                "english": ["Thursday"],
                "meaning": "목요일"
            },
            {
                "title": "DAY 1 날짜",
                "chapter": "요일",
                "level": "N5",
                "wordClass": "명사",
                "korean": "금요일",
                "japanese": ["きんようび", "金よう日"],
                "hiragana": ["きんようび"],
                "katakana": [],
                "kanzi": ["金曜日"],
                "english": ["Friday"],
                "meaning": "금요일"
            },
            {
                "title": "DAY 1 날짜",
                "chapter": "요일",
                "level": "N5",
                "wordClass": "명사",
                "korean": "토요일",
                "japanese": ["どようび", "土よう日"],
                "hiragana": ["どようび"],
                "katakana": [],
                "kanzi": ["土曜日"],
                "english": ["Saturday"],
                "meaning": "토요일"
            },
            {
                "title": "DAY 1 날짜",
                "chapter": "요일",
                "level": "N5",
                "wordClass": "명사",
                "korean": "일요일",
                "japanese": ["にちようび", "日よう日"],
                "hiragana": ["にちようび"],
                "katakana": [],
                "kanzi": ["日曜日"],
                "english": ["Sunday"],
                "meaning": "일요일"
            },
            {
                "title": "DAY 1 날짜",
                "chapter": "요일",
                "level": "N5",
                "wordClass": "명사",
                "korean": "무슨 요일",
                "japanese": ["なんようび", "何よう日"],
                "hiragana": ["なんようび"],
                "katakana": [],
                "kanzi": ["何曜日"],
                "english": ["what day of the week"],
                "meaning": "무슨 요일"
            }
        ],
        skipDuplicates: true,
    });
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    }); 